//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace EKS.Entity
{
    using System;
    using System.Collections.Generic;
    
    public partial class BACKUPANDRECOVERTABLE
    {
        public int ID { get; set; }
        public string BOLGE { get; set; }
        public string MAKINA { get; set; }
        public string BILGISAYAR_BILGISI { get; set; }
        public string OTOMASYON_IP { get; set; }
        public string BILGISAYAR_IP { get; set; }
        public string YEDEK_ADI { get; set; }
        public string YEDEGI_ALAN_PERSONEL { get; set; }
        public System.DateTime YEDEKLEME_TARIHI { get; set; }
        public System.DateTime KAYIT_TARIHI { get; set; }
        public string YEDEKLEME_TIPI { get; set; }
        public string YEDEKLEME_PROGRAM_VERSIYONU { get; set; }
        public string ISLETIM_SISTEMI_BILGISI { get; set; }
        public string HARDDISK_BILGISI { get; set; }
        public string ACIKLAMALAR { get; set; }
        public string TALIMAT_BILGISI { get; set; }
    }
}
