CREATE TABLE [dbo].[USERS](
	[USERID] [int] IDENTITY(1,1) NOT NULL,
	[NAME] [nchar](10) NOT NULL,
	[LASTNAME] [nchar](10) NOT NULL,
	[USERNAME] [nchar](10) NOT NULL,
	[PASSWORD] [nvarchar](50) NOT NULL,
	[AUTHORITY] varchar(25) default 'UNKNOWN USER'
	Constraint _AUT Check ([AUTHORITY] IN('ADMIN', 'USER', 'OTHER USER', 'UNKNOWN USER'))
) ON [PRIMARY]

insert into USERS(NAME, LASTNAME, USERNAME, PASSWORD, AUTHORITY) values('N', 'Ö', 'E', '1', 'ADMIN')
