//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace EKS.Database_Tools
{
    using System;
    using System.Collections.Generic;
    
    public partial class BACKUPANDRECOVERTABLE
    {
        public int ID { get; set; }
        public string BOLGE { get; set; }
        public string MAKINA { get; set; }
        public string BILGISAYAR_LOKASYONU { get; set; }
        public string BACKUP_ADI { get; set; }
        public System.DateTime BACKUP_TARIHI { get; set; }
        public string BACKUP_PROGRAM_ADI { get; set; }
        public string BACKUP_TIPI { get; set; }
        public string BACKUP_VERSIYONU { get; set; }
        public Nullable<System.DateTime> KAYIT_TARIHI { get; set; }
        public string BACKUP_ALAN_PERSONEL { get; set; }
        public string BACKUP_NEDENI { get; set; }
        public string BILGISAYAR_MODELI { get; set; }
        public string ISLETIM_SISTEMI { get; set; }
        public string HARDDISK_BILGISI { get; set; }
        public string OTOMASYON_IP { get; set; }
        public string MAKINA_IP { get; set; }
        public string PETLAS_IP { get; set; }
        public string LISANS_DOSYASI { get; set; }
        public string ACIKLAMALAR { get; set; }
    }
}
