//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace EKS.Database_Tools
{
    using System;
    using System.Collections.Generic;
    
    public partial class USERS
    {
        public int USERID { get; set; }
        public string NAME { get; set; }
        public string LASTNAME { get; set; }
        public string USERNAME { get; set; }
        public string PASSWORD { get; set; }
        public string AUTHORITY { get; set; }
    }
}
